apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-pgadmin
  namespace: standard
  labels:
    app: exam-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-pgadmin
  template:
    metadata:
      labels:
        app: exam-pgadmin
    spec:
      containers:
        - name: exam-pgadmin
          image: "dpage/pgadmin4:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: exam-pgadmin
              containerPort: 80
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: exam-pgadmin
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: exam-pgadmin
                  key: PGADMIN_DEFAULT_PASSWORD
