apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: standard
  labels:
    app: exam-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: exam-postgres
  selector:
    app: exam-postgres
